
// This file has been generated by the GUI designer. Do not modify.

public partial class SketchWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action newAction;
	private global::Gtk.Action openAction;
	private global::Gtk.Action saveAction;
	private global::Gtk.Action saveAsAction;
	private global::Gtk.Action undoAction;
	private global::Gtk.Action redoAction;
	private global::Gtk.Action gotoFirstAction;
	private global::Gtk.Action goBackAction;
	private global::Gtk.Action goForwardAction;
	private global::Gtk.Action gotoLastAction;
	private global::Gtk.Action mediaPlayAction;
	private global::Gtk.Action mediaStopAction;
	private global::Gtk.Action addAction;
	private global::Gtk.Action removeAction;
	private global::Gtk.Action undoAction1;
	private global::Gtk.Action redoAction1;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action newAction1;
	private global::Gtk.Action openAction1;
	private global::Gtk.Action saveAction1;
	private global::Gtk.Action saveAsAction1;
	private global::Gtk.Action EditAction;
	private global::Gtk.Action undoAction2;
	private global::Gtk.Action redoAction2;
	private global::Gtk.Action FrameAction;
	private global::Gtk.Action addAction1;
	private global::Gtk.Action removeAction1;
	private global::Gtk.Action gotoFirstAction1;
	private global::Gtk.Action goBackAction1;
	private global::Gtk.Action goForwardAction1;
	private global::Gtk.Action gotoLastAction1;
	private global::Gtk.Action AnimationAction;
	private global::Gtk.Action mediaPlayAction1;
	private global::Gtk.Action mediaStopAction1;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Toolbar toolbar2;
	private global::Sketch.SketchControl sketchcontrol1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget SketchWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.newAction = new global::Gtk.Action ("newAction", null, null, "gtk-new");
		w1.Add (this.newAction, null);
		this.openAction = new global::Gtk.Action ("openAction", null, null, "gtk-open");
		w1.Add (this.openAction, null);
		this.saveAction = new global::Gtk.Action ("saveAction", null, null, "gtk-save");
		w1.Add (this.saveAction, null);
		this.saveAsAction = new global::Gtk.Action ("saveAsAction", null, null, "gtk-save-as");
		w1.Add (this.saveAsAction, null);
		this.undoAction = new global::Gtk.Action ("undoAction", null, null, "gtk-undo");
		w1.Add (this.undoAction, null);
		this.redoAction = new global::Gtk.Action ("redoAction", null, null, "gtk-redo");
		w1.Add (this.redoAction, null);
		this.gotoFirstAction = new global::Gtk.Action ("gotoFirstAction", null, null, "gtk-goto-first");
		w1.Add (this.gotoFirstAction, null);
		this.goBackAction = new global::Gtk.Action ("goBackAction", null, null, "gtk-go-back");
		w1.Add (this.goBackAction, null);
		this.goForwardAction = new global::Gtk.Action ("goForwardAction", null, null, "gtk-go-forward");
		w1.Add (this.goForwardAction, null);
		this.gotoLastAction = new global::Gtk.Action ("gotoLastAction", null, null, "gtk-goto-last");
		w1.Add (this.gotoLastAction, null);
		this.mediaPlayAction = new global::Gtk.Action ("mediaPlayAction", null, null, "gtk-media-play");
		w1.Add (this.mediaPlayAction, null);
		this.mediaStopAction = new global::Gtk.Action ("mediaStopAction", null, null, "gtk-media-stop");
		w1.Add (this.mediaStopAction, null);
		this.addAction = new global::Gtk.Action ("addAction", null, null, "gtk-add");
		w1.Add (this.addAction, null);
		this.removeAction = new global::Gtk.Action ("removeAction", null, null, "gtk-remove");
		w1.Add (this.removeAction, null);
		this.undoAction1 = new global::Gtk.Action ("undoAction1", null, null, "gtk-undo");
		w1.Add (this.undoAction1, null);
		this.redoAction1 = new global::Gtk.Action ("redoAction1", null, null, "gtk-redo");
		w1.Add (this.redoAction1, null);
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.newAction1 = new global::Gtk.Action ("newAction1", global::Mono.Unix.Catalog.GetString ("_New"), null, "gtk-new");
		this.newAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_New");
		w1.Add (this.newAction1, null);
		this.openAction1 = new global::Gtk.Action ("openAction1", global::Mono.Unix.Catalog.GetString ("Open..."), null, "gtk-open");
		this.openAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open...");
		w1.Add (this.openAction1, null);
		this.saveAction1 = new global::Gtk.Action ("saveAction1", global::Mono.Unix.Catalog.GetString ("Save"), null, "gtk-save");
		this.saveAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.saveAction1, null);
		this.saveAsAction1 = new global::Gtk.Action ("saveAsAction1", global::Mono.Unix.Catalog.GetString ("Save As..."), null, "gtk-save-as");
		this.saveAsAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save As...");
		w1.Add (this.saveAsAction1, null);
		this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction, null);
		this.undoAction2 = new global::Gtk.Action ("undoAction2", global::Mono.Unix.Catalog.GetString ("Undo"), null, "gtk-undo");
		this.undoAction2.ShortLabel = global::Mono.Unix.Catalog.GetString ("Undo");
		w1.Add (this.undoAction2, "<Control>y");
		this.redoAction2 = new global::Gtk.Action ("redoAction2", global::Mono.Unix.Catalog.GetString ("_Redo"), null, "gtk-redo");
		this.redoAction2.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Redo");
		w1.Add (this.redoAction2, null);
		this.FrameAction = new global::Gtk.Action ("FrameAction", global::Mono.Unix.Catalog.GetString ("Frame"), null, null);
		this.FrameAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Frame");
		w1.Add (this.FrameAction, null);
		this.addAction1 = new global::Gtk.Action ("addAction1", global::Mono.Unix.Catalog.GetString ("Add"), null, "gtk-add");
		this.addAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add");
		w1.Add (this.addAction1, null);
		this.removeAction1 = new global::Gtk.Action ("removeAction1", global::Mono.Unix.Catalog.GetString ("Delete"), null, "gtk-remove");
		this.removeAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Delete");
		w1.Add (this.removeAction1, null);
		this.gotoFirstAction1 = new global::Gtk.Action ("gotoFirstAction1", global::Mono.Unix.Catalog.GetString ("First"), null, "gtk-goto-first");
		this.gotoFirstAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("First");
		w1.Add (this.gotoFirstAction1, null);
		this.goBackAction1 = new global::Gtk.Action ("goBackAction1", global::Mono.Unix.Catalog.GetString ("Previous"), null, "gtk-go-back");
		this.goBackAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Previous");
		w1.Add (this.goBackAction1, null);
		this.goForwardAction1 = new global::Gtk.Action ("goForwardAction1", global::Mono.Unix.Catalog.GetString ("Next"), null, "gtk-go-forward");
		this.goForwardAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Next");
		w1.Add (this.goForwardAction1, null);
		this.gotoLastAction1 = new global::Gtk.Action ("gotoLastAction1", global::Mono.Unix.Catalog.GetString ("Last"), null, "gtk-goto-last");
		this.gotoLastAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Last");
		w1.Add (this.gotoLastAction1, null);
		this.AnimationAction = new global::Gtk.Action ("AnimationAction", global::Mono.Unix.Catalog.GetString ("Animation"), null, null);
		this.AnimationAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Animation");
		w1.Add (this.AnimationAction, null);
		this.mediaPlayAction1 = new global::Gtk.Action ("mediaPlayAction1", global::Mono.Unix.Catalog.GetString ("Play"), null, "gtk-media-play");
		this.mediaPlayAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Play");
		w1.Add (this.mediaPlayAction1, null);
		this.mediaStopAction1 = new global::Gtk.Action ("mediaStopAction1", global::Mono.Unix.Catalog.GetString ("Stop"), null, "gtk-media-stop");
		this.mediaStopAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Stop");
		w1.Add (this.mediaStopAction1, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "SketchWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		this.BorderWidth = ((uint)(10));
		this.AllowShrink = true;
		// Container child SketchWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar2'><toolitem name='newAction' action='newAction'/><toolitem name='openAction' action='openAction'/><toolitem name='saveAction' action='saveAction'/><toolitem name='saveAsAction' action='saveAsAction'/><separator/><toolitem name='undoAction1' action='undoAction1'/><toolitem name='redoAction1' action='redoAction1'/><separator/><toolitem name='addAction' action='addAction'/><toolitem name='removeAction' action='removeAction'/><separator/><toolitem name='gotoFirstAction' action='gotoFirstAction'/><toolitem name='goBackAction' action='goBackAction'/><toolitem name='goForwardAction' action='goForwardAction'/><toolitem name='gotoLastAction' action='gotoLastAction'/><separator/><toolitem name='mediaPlayAction' action='mediaPlayAction'/><toolitem name='mediaStopAction' action='mediaStopAction'/></toolbar></ui>");
		this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar2")));
		this.toolbar2.Name = "toolbar2";
		this.toolbar2.ShowArrow = false;
		this.toolbar2.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.toolbar2.IconSize = ((global::Gtk.IconSize)(2));
		this.vbox2.Add (this.toolbar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.toolbar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.sketchcontrol1 = new global::Sketch.SketchControl ();
		this.sketchcontrol1.WidthRequest = 400;
		this.sketchcontrol1.HeightRequest = 300;
		this.sketchcontrol1.Name = "sketchcontrol1";
		this.sketchcontrol1.Preview = false;
		this.vbox2.Add (this.sketchcontrol1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.sketchcontrol1]));
		w3.Position = 1;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
<<<<<<< HEAD
		this.DefaultWidth = 752;
		this.DefaultHeight = 400;
=======
		this.DefaultWidth = 995;
		this.DefaultHeight = 406;
>>>>>>> f38be9216120f5f8f81d08a912708d70b6e8e073
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.newAction.Activated += new global::System.EventHandler (this.OnNewActionActivated);
		this.openAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.saveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
		this.saveAsAction.Activated += new global::System.EventHandler (this.OnSaveAsActionActivated);
		this.gotoFirstAction.Activated += new global::System.EventHandler (this.OnGotoFirstActionActivated);
		this.goBackAction.Activated += new global::System.EventHandler (this.OnGoBackActionActivated);
		this.goForwardAction.Activated += new global::System.EventHandler (this.OnGoForwardActionActivated);
		this.gotoLastAction.Activated += new global::System.EventHandler (this.OnGotoLastActionActivated);
		this.mediaPlayAction.Activated += new global::System.EventHandler (this.OnMediaPlayActionActivated);
		this.mediaStopAction.Activated += new global::System.EventHandler (this.OnMediaStopActionActivated);
		this.addAction.Activated += new global::System.EventHandler (this.OnAddActionActivated);
		this.removeAction.Activated += new global::System.EventHandler (this.OnRemoveActionActivated);
		this.undoAction1.Activated += new global::System.EventHandler (this.OnUndoAction1Activated);
		this.redoAction1.Activated += new global::System.EventHandler (this.OnRedoAction1Activated);
	}
}
